apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: port-package-parser
  annotations:
spec:
  templates:
    - name: package-parser
      serviceAccountName: port-executor
      metadata:
        annotations:
          port/description: "Parse packages according to definition and export resulting identifiers"
      inputs:
        parameters:
          - name: REPO_URL
          - name: GIT_TOKEN_SECRET
          - name: GIT_TOKEN_SECRET_KEY
            default: token
          - name: PORT_CREDENTIALS_SECRET
            default: port-credentials
          - name: PORT_CLIENT_ID_KEY
            default: PORT_CLIENT_ID
          - name: PORT_CLIENT_SECRET_KEY
            default: PORT_CLIENT_SECRET
          - name: PACKAGES_FILE_PATH
          - name: PACKAGE_FILTER_STRING
            default: ""
      container:
        name: main
        imagePullPolicy: Always
        image: public.ecr.aws/y8q1v8m0/codefresh-package-parser:1.0.0
        command:
          - python3
          - main.py
        env:
          - name: REPO_URL
            value: "{{ inputs.parameters.REPO_URL }}"
          - name: ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{ inputs.parameters.GIT_TOKEN_SECRET }}"
                key: "{{ inputs.parameters.GIT_TOKEN_SECRET_KEY }}"
          - name: PORT_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: "{{ inputs.parameters.PORT_CREDENTIALS_SECRET }}"
                key: "{{ inputs.parameters.PORT_CLIENT_ID_KEY }}"
          - name: PORT_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{ inputs.parameters.PORT_CREDENTIALS_SECRET }}"
                key: "{{ inputs.parameters.PORT_CLIENT_SECRET_KEY }}"
          - name: PACKAGE_MANAGER
            value: "C_SHARP_PROJECT"
          - name: PACKAGES_FILE_PATH
            value: "{{ inputs.parameters.PACKAGES_FILE_PATH }}"
          - name: PACKAGE_FILTER_STRING
            value: "{{ inputs.parameters.PACKAGE_FILTER_STRING }}"
      outputs:
        parameters:
          - name: PARSED_PACKAGES_ARRAY
            valueFrom:
              path: /tmp/packagevars/PARSED_PACKAGES_ARRAY
            globalName: PARSED_PACKAGES_ARRAY
