apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: port.codefresh-package-parser.0.0.1
  annotations:
    port/version: "0.0.1"
    port/description: "This Workflow Template is used to parse packages form a package definition file in a target Git repo, create matching entities in Port and then return those entity identifiers as an array output"
spec:
  arguments:
    parameters:
  entrypoint: ci-tasks
  templates:
    - name: ci-tasks
      metadata:
        annotations:
      dag:
        tasks:
          - name: parse-and-report-packages
            templateRef:
              name: port-package-parser
              template: package-parser
            arguments:
              parameters:
                - name: REPO_URL
                  value: bitbucket.org/port-labs/package-reporting-demo.git
                - name: GIT_TOKEN_SECRET
                  value: bitbucket-access-token
                - name: PORT_CREDENTIALS_SECRET
                  value: port-credentials
                - name: PORT_CLIENT_ID_KEY
                  value: PORT_CLIENT_ID
                - name: PORT_CLIENT_SECRET_KEY
                  value: PORT_CLIENT_SECRET
                - name: PACKAGES_FILE_PATH
                  value: apps/api/apps/api/Port.API.Microservice.csproj
                - name: PACKAGE_FILTER_STRING
                  value: "Port"
                - name: PACKAGE_MANAGER
                  default: C_SHARP
                - name: PACKAGES_FILE_FILTER
                - name: INTERNAL_PACKAGE_FILTERS
                  default: ""
                - name: TARGET_BLUEPRINT_IDENTIFIER
                  default: null
                - name: TARGET_ENTITY_IDENTIFIER
                  default: null
          - name: log-info
            dependencies: [parse-and-report-packages]
            template: log-info
            arguments:
              parameters:
                - name: INFO
                  value: "{{workflow.outputs.parameters.PARSED_PACKAGES_ARRAY}}"
          - name: entity-upsert
            dependencies: [parse-and-report-packages]
            templateRef:
              name: port
              template: entity-upsert
            arguments:
              parameters:
                - name: BLUEPRINT_IDENTIFIER
                  value: "deployed-service"
                - name: ENTITY_IDENTIFIER
                  value: "morp"
                - name: ENTITY_PROPERTIES
                  value: |
                    {
                      "status": {"test": true}
                    }
                - name: ENTITY_RELATIONS
                  value: |
                    {
                      "library-releases": {{workflow.outputs.parameters.PARSED_PACKAGES_ARRAY}}
                    }

    - name: log-info
      inputs:
        parameters:
          - name: INFO
      script:
        image: alpine:latest
        command: ["/bin/sh"]
        env:
          - name: INFO
            value: "{{ inputs.parameters.INFO }}"
        source: |
          set -e
          echo ${INFO}
